-- 코드를 입력하세요
SELECT CART_ID
FROM (
    SELECT CART_ID, COUNT(DISTINCT NAME) AS CNT
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk' OR NAME = 'Yogurt'
    GROUP BY CART_ID
    ) AS sub
WHERE CNT = 2
ORDER BY CART_ID