SELECT
    R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM REST_INFO R
JOIN (
    SELECT
        FOOD_TYPE,
        MAX(FAVORITES) AS MAX_FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) I
ON R.FOOD_TYPE = I.FOOD_TYPE
AND R.FAVORITES = I.MAX_FAVORITES
ORDER BY R.FOOD_TYPE DESC;
