-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, GENDER, COUNT(DISTINCT us.USER_ID) AS USERS
FROM (USER_INFO as us INNER JOIN ONLINE_SALE as os ON us.USER_ID = os.USER_ID) 
WHERE GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER

# SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT us.USER_ID)
# FROM (USER_INFO as us INNER JOIN ONLINE_SALE as os ON us.USER_ID = os.USER_ID) 
# WHERE GENDER IS NOT NULL