-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT half.FLAVOR AS FLAVOR, half.TOTAL_ORDER + jul.TOTAL_ORDER AS ORDER_SUM
    FROM (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM FIRST_HALF 
        GROUP BY FLAVOR
    ) AS half
    JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY 
        GROUP BY FLAVOR
    ) AS jul
        ON half.FLAVOR = jul.FLAVOR
) AS final
ORDER BY ORDER_SUM DESC
LIMIT 3