-- 코드를 입력하세요
SELECT prof.MEMBER_NAME, rev.REVIEW_TEXT, DATE_FORMAT(rev.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM (REST_REVIEW rev INNER JOIN MEMBER_PROFILE prof ON rev.MEMBER_ID = prof.MEMBER_ID) 
WHERE rev.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
)
ORDER BY REVIEW_DATE, REVIEW_TEXT