SELECT MONTH(his.START_DATE) AS MONTH, his.CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID) >= 5
    ) as c INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY as his ON c.CAR_ID = his.CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(his.START_DATE), his.CAR_ID
ORDER BY MONTH ASC, his.CAR_ID DESC