SELECT 
    D.ID, 
    D.EMAIL, 
    D.FIRST_NAME, 
    D.LAST_NAME
FROM 
    DEVELOPERS D
JOIN 
    SKILLCODES S_PYTHON
    ON (D.SKILL_CODE & S_PYTHON.CODE) = S_PYTHON.CODE
    AND S_PYTHON.NAME = 'Python'
    
UNION

SELECT 
    D.ID, 
    D.EMAIL, 
    D.FIRST_NAME, 
    D.LAST_NAME
FROM 
    DEVELOPERS D
JOIN 
    SKILLCODES S_CSHARP
    ON (D.SKILL_CODE & S_CSHARP.CODE) = S_CSHARP.CODE
    AND S_CSHARP.NAME = 'C#'
ORDER BY 
    ID;
