SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, COLS.MAX_COL - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS ORIGIN INNER JOIN
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) as MAX_COL
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) AS COLS ON YEAR(ORIGIN.DIFFERENTIATION_DATE) = COLS.YEAR
ORDER BY YEAR, YEAR_DEV