-- 코드를 입력하세요
SELECT half.FLAVOR
FROM FIRST_HALF half, ICECREAM_INFO info
WHERE half.FLAVOR = info.FLAVOR
  AND half.TOTAL_ORDER > 3000
  AND info.INGREDIENT_TYPE = 'fruit_based'
ORDER BY half.TOTAL_ORDER DESC;
