-- 코드를 입력하세요
SELECT half.FLAVOR
FROM FIRST_HALF AS half INNER JOIN ICECREAM_INFO AS info ON half.FLAVOR = info.FLAVOR
WHERE TOTAL_ORDER > 3000 and INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC