-- 코드를 입력하세요
SELECT his.CAR_ID
FROM (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE MONTH(START_DATE) = '10'
    ) as his INNER JOIN CAR_RENTAL_COMPANY_CAR as car ON his.CAR_ID = car.CAR_ID 
WHERE CAR_TYPE = '세단'
ORDER BY CAR_ID DESC
