SELECT CONCAT('/home/grep/src/', f.BOARD_ID, '/', f.FILE_ID, f.FILE_NAME, f.FILE_EXT) AS FILE_PATH
FROM (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
    ) AS b, USED_GOODS_FILE AS f
WHERE b.BOARD_ID = f.BOARD_ID
ORDER BY FILE_ID DESC