-- 코드를 입력하세요
SELECT FP.CATEGORY, MAX_P.MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP INNER JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    ) AS MAX_P ON FP.PRICE = MAX_P.MAX_PRICE AND FP.CATEGORY = MAX_P.CATEGORY
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_P.MAX_PRICE DESC

